import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/SmoothScroll";
import MouseGlow from "./components/MouseGlow";
import CustomCursor from "./components/CustomCursor";
import Loader from "./components/Loader";
import PageReveal from "./components/PageReveal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative `}
      >
        <Loader />
        <PageReveal />
        <CustomCursor />
        {/* <MouseGlow /> */}
        <div className="grid-overlay" />
        <div className="noise-overlay" />
        <SmoothScroll> {children}</SmoothScroll>
      </body>
    </html>
  );
}
